### PR TITLE
break up index.js into files per class

### PR DESCRIPTION
**Pull request by mzgoddard**
### Proposed changes

Break up index.js into separate files
- Add AudioEngine.js
- Add AudioPlayer.js
- Add Loudness.js

### Reason for changes

Some code organization before adding tests and overhauling scratch-audio with a different architecture.

### CODE REVIEW

**Review by rschamp — APPROVED** [review]
LGTM!

**Comment by rschamp** [comment]
(but @ericrosenbaum should look before merging)

**Review by gnarf — APPROVED** [review]
nice simple one to get rolling with :)

**Review by ericrosenbaum — APPROVED** [review]
👍

**Pull request merged**
