### PR TITLE
Add mic input for loudness block

### PR DESCRIPTION
**Pull request by ericrosenbaum**
### Proposed changes

Add a getLoudness function, for use by the loudness reporter block. It measures the sound in RMS and smooths it slightly.

### Reason for changes

Implementing the existing loudness block, which will require another small PR in the VM.

### CODE REVIEW

**Comment by paulkaplan** [comment]
@ericrosenbaum why -1 loudness if it isn't available? Wouldn't it just be 0?

**Comment by ericrosenbaum** [comment]
@paulkaplan That's to match the Scratch 2.0 behavior, and not break existing projects that rely on it (I would have missed this at first if not for a helpful comment from @liam4)

**Comment by paulkaplan** [comment]
@ericrosenbaum I tried using this but it fails, I believe there is some kind of version mismatch going on. The package.json lists a hard dependency on 0.8.0, while it seems that `Tone.UserMedia` was introduced in 0.9.0. 

https://github.com/Tonejs/Tone.js/releases/tag/r9

**Comment by paulkaplan** [comment]
LG

**Comment by paulkaplan** [comment]
For posterity: @ericrosenbaum and I talked about how we might replicate this behavior without the Tone.js library. It will be pretty straightforward after we have our recording stuff in.

**Review by paulkaplan — APPROVED** [review]

**Pull request merged**
